[project]
name = "atp2osm-import"
version = "0.1.0"
description = "Import ATP FR data into OSM"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "argparse>=1.4.0",
    "duckdb>=1.4.3",
    "logging>=0.4.9.6",
    "psycopg2-binary>=2.9.11",
    "requests>=2.32.5",
]
